### ISSUE TITLE
Adding a Model for categorising complaints

### ISSUE THREAD

**Issue by ShouryaMishra2006** [ContriHUB/EAT_EASY#6]
🚀Feature Request
I have a suggestion (and may want to implement it 🙂)!
I want to add a model to The complaints Section for the accountant profile side that will classify the complaints into critical and low that will tell the accountant that which complaints need immediate attention and action and which need to be resolved first that will also save the time of accountant.
I am going to build and Train the Model using Hugging face Transformers , NLTK.

**Comment by Codipk** [comment]
Yeahh It is a great idea but to categrize the complaints I have used voting feature which itself reflect the most voted complaints is the critical one and since it's a MERN based project so personallly I don't want this if u want u can fork the repo and can implement these features in your own repo.
